KBVault.Web/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KBVault.Dal;
using KBVault.Web.Models;

namespace KBVault.Web.Controllers
{
    [Authorize]
    public class ActivityController : KbVaultAdminController
    {
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpPost]
        public JsonResult Get(ActivityDataTablesPostModel model)
        {
            try
            {
                var length = model.length;
                var page = model.start / length;
                var result = new JsonOperationResponse();
                using (var db = new KbVaultContext())
                {
                    var recordCount = db.Activities.Count();
                    db.Configuration.LazyLoadingEnabled = false;
                    var activities = db.Activities.Include("KbUser")
                                    .OrderByDescending(a => a.ActivityDate)
                                    .Skip(page * length)
                                    .Take(length).AsEnumerable()
                                    .Select(a => new ActivityViewModel
                                    {
                                        ActivityDate = a.ActivityDate.ToString("dd/MM/yyyy H:mm"),
                                        Operation = a.Operation,
                                        Text = a.Information,
                                        User = a.KbUser.Name + " " + a.KbUser.LastName
                                    }).ToList();
                    result.Successful = true;
                    result.Data = activities;
                    return Json(new { recordsFiltered = recordCount, recordsTotal = recordCount, Successfull = result.Successful, ErrorMessage = result.ErrorMessage, data = ((List<ActivityViewModel>)result.Data).Select(aw => new[] { aw.ActivityDate, aw.Operation, aw.Text, aw.User }) }, JsonRequestBehavior.DenyGet);
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                throw;
            }
        }
    }
}

KBVault.Web/Controllers/BackupController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Core.EntityClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using KBVault.Backup;
using KBVault.Backup.Classes;
using KBVault.Backup.Interface;
using KBVault.Web.Models;
using Resources;

namespace KBVault.Web.Controllers
{
    public class BackupController : KbVaultAdminController
    {
        public ActionResult Index()
        {
            var backupDirectory = string.Empty;
            if (!string.IsNullOrEmpty(Settings.BackupPath) && Settings.BackupPath.StartsWith("~"))
            {
                backupDirectory = Server.MapPath(Settings.BackupPath);
            }
            else
            {
                backupDirectory = Settings.BackupPath;
            }

            var model = new List<BackupListViewModel>();
            var i = 0;
            if (!string.IsNullOrEmpty(backupDirectory))
            {
                foreach (var filePath in Directory.GetFiles(backupDirectory, "*.bak"))
                {
                    var fo = new FileInfo(filePath);
                    model.Add(new BackupListViewModel
                    {
                        Id = i,
                        FileName = Path.GetFileName(filePath),
                        FileDate = fo.CreationTime
                    });
                    i++;
                }
            }

            return View(model.OrderByDescending(f => f.FileDate));
        }

        [HttpPost]
        public JsonResult Restore(string file)
        {
            try
            {
                var result = new JsonOperationResponse();
                try
                {
                    var backupFile = string.Empty;
                    if (Settings.BackupPath.StartsWith("~"))
                    {
                        backupFile = Server.MapPath(Settings.BackupPath + file);
                    }
                    else
                    {
                        backupFile = Settings.BackupPath + file;
                    }

                    if (System.IO.File.Exists(backupFile))
                    {
                        var connectionString = ConfigurationManager.ConnectionStrings["KbVaultEntities"].ConnectionString;
                        var entityConnectionString = new EntityConnectionStringBuilder(connectionString);
                        var builder = new System.Data.SqlClient.SqlConnectionStringBuilder(entityConnectionString.ProviderConnectionString);

                        IVaultBackup backup = new VaultMsSqlBackup();
                        backup.Connect(entityConnectionString.ProviderConnectionString);
                        result.Successful = backup.Restore(builder.InitialCatalog, backupFile);
                        if (result.Successful)
                        {
                            result.ErrorMessage = UIResources.BackupRestoreSuccessfull;
                        }
                    }
                    else
                    {
                        throw new FileNotFoundException(file);
                    }
                }
                catch (Exception ex)
                {
                    Log.Error(ex);
                    result.ErrorMessage = ex.Message;
                }

                return Json(result, JsonRequestBehavior.DenyGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                throw;
            }
        }

        [HttpPost]
        public JsonResult BackupNow()
        {
            try
            {
                var result = new JsonOperationResponse();
                if (string.IsNullOrEmpty(Settings.BackupPath))
                {
                    result.Successful = false;
                    result.ErrorMessage = ErrorMessages.BackupPathIsNotSet;
                }
                else
                {
                    var connectionString = ConfigurationManager.ConnectionStrings["KbVaultContext"].ConnectionString;
                    var builder = new System.Data.SqlClient.SqlConnectionStringBuilder(connectionString);
                    IVaultBackup backup = new VaultMsSqlBackup();
                    backup.Connect(connectionString);
                    var backupFile = string.Format("{0:yyyyMddhhmm}.bak", DateTime.Now);
                    if (!string.IsNullOrEmpty(Settings.BackupPath) && Settings.BackupPath.StartsWith("~"))
                    {
                        backupFile = Server.MapPath(Settings.BackupPath + backupFile);
                    }
                    else
                    {
                        backupFile = Settings.BackupPath + backupFile;
                    }

                    var backupSuccessful = backup.Backup(builder.InitialCatalog, backupFile);
                    if (backupSuccessful)
                    {
                        if (!string.IsNullOrEmpty(backupFile))
                        {
                            result.Data = backupFile;
                            result.Successful = true;
                        }
                    }
                }

                return Json(result, JsonRequestBehavior.DenyGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                throw;
            }
        }
    }
}

KBVault.Web/Controllers/SearchController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using KBVault.Dal;
using KBVault.Dal.Entities;
using KBVault.Web.Helpers;
using KBVault.Web.Models;
using KBVault.Web.Models.Public;

namespace KBVault.Web.Controllers
{
    public class SearchController : KbVaultPublicController
    {
        [HttpPost]
        public ActionResult Do(SearchFormViewModel model)
        {
            try
            {
                if (string.IsNullOrEmpty(model.SearchKeyword))
                {
                    return RedirectToAction("Index", "Home");
                }

                var articlePrefix = SettingsService.GetSettings().ArticlePrefix;
                if (!string.IsNullOrEmpty(articlePrefix))
                {
                    if (model.SearchKeyword.Length > articlePrefix.Length + 1 &&
                        model.SearchKeyword.Substring(0, articlePrefix.Length + 1) == articlePrefix + "-")
                    {
                        var articleId = model.SearchKeyword.Substring(articlePrefix.Length + 1);
                        model.ArticleId = Convert.ToInt32(articleId);
                    }

                    if (model.ArticleId > 0)
                    {
                        Article article = null;
                        using (var db = new KbVaultContext())
                        {
                            article = db.PublishedArticles().FirstOrDefault(a => a.Id == model.ArticleId);
                        }

                        if (article != null)
                        {
                            return RedirectToRoute("Default", new { controller = "Home", action = "Detail", id = article.SefName });
                        }
                    }
                }

                if (model.CurrentPage == 0)
                {
                    model.CurrentPage++;
                }

                model.Results = KbVaultLuceneHelper.DoSearch(model.SearchKeyword, model.CurrentPage, 10);

                return View(model);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                throw;
            }
        }

        [HttpPost]
        public JsonResult More(SearchFormViewModel model)
        {
            var result = new JsonOperationResponse();
            try
            {
                model.CurrentPage++;
                model.Results = KbVaultLuceneHelper.DoSearch(model.SearchKeyword, model.CurrentPage, 1);
                result.Successful = true;
                result.Data = model;
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                result.ErrorMessage = ex.Message;
            }

            return Json(result);
        }

        [HttpPost]
        public JsonResult Ajax(string id)
        {
            var result = new JsonOperationResponse();
            try
            {
                if (Request.IsAjaxRequest())
                {
                    var items = KbVaultLuceneHelper.DoSearch(id, 1, 10);
                    result.Data = items;
                    result.Successful = true;
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                result.ErrorMessage = ex.Message;
            }

            return Json(result);
        }
    }
}

KBVault.Web/Controllers/TagController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using KBVault.Dal;
using KBVault.Dal.Repository;
using KBVault.Web.Helpers;
using KBVault.Web.Models;
using MvcPaging;
using Resources;

namespace KBVault.Web.Controllers
{
    [Authorize(Roles="Admin,Manager")]
    public class TagController : KbVaultAdminController
    {
        private const int PageSize = 45;

        public ITagRepository TagRepository { get; set; }

        [HttpPost]
        public JsonResult Edit(string pk, string value)
        {
            var result = new JsonOperationResponse();
            try
            {
                using (var db = new KbVaultContext())
                {
                    var tagId = Convert.ToInt64(pk);
                    var tag = db.Tags.First(t => t.Id == tagId);
                    if (tag != null)
                    {
                        tag.Author = KBVaultHelperFunctions.UserAsKbUser(User).Id;
                        tag.Name = value;
                        db.SaveChanges();
                        result.Successful = true;
                        return Json(result);
                    }
                }

                return null;
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                result.Successful = false;
                result.ErrorMessage = ex.Message;
                return Json(result);
            }
        }

        [HttpPost]
        public JsonResult Remove(int id = -1)
        {
            var result = new JsonOperationResponse
            {
                Successful = false
            };
            try
            {
                using (var db = new KbVaultContext())
                {
                    var tag = db.Tags.First(t => t.Id == id);
                    if (tag != null)
                    {
                        tag.Author = KBVaultHelperFunctions.UserAsKbUser(User).Id;
                        db.Tags.Remove(tag);
                        TagRepository.RemoveTagFromArticles(id);
                        db.SaveChanges();
                        result.Successful = true;
                        result.ErrorMessage = UIResources.TagListRemoveSuccessful;
                    }
                    else
                    {
                        result.ErrorMessage = ErrorMessages.TagNotFound;
                    }
                }

                return Json(result);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                result.ErrorMessage = ex.Message;
                return Json(result);
            }
        }

        public ActionResult List(int page = 1)
        {
            try
            {
                if (page < 1)
                {
                    page = 1;
                }

                using (var db = new KbVaultContext())
                {
                    return View(db.Tags.OrderBy(t => t.Name).ToPagedList(page, PageSize));
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("Index", "Error");
            }
        }

        [Authorize(Roles="Admin,Manager,Editor")]
        public JsonResult Suggest(string term)
        {
            var result = new JsonOperationResponse();
            try
            {
                using (var db = new KbVaultContext())
                {
                    var suggestions = db.Tags.Where(t => t.Name.Contains(term)).Select(t => t.Name).Take(20).ToList<string>();
                    result.Successful = true;
                    result.Data = suggestions.ToArray();
                    return Json(result);
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                result.Successful = false;
                result.ErrorMessage = ex.Message;
                return Json(result);
            }
        }
    }
}

KBVault.Web/Views/Shared/GoogleFonts.cshtml
@if( Request.IsSecureConnection )
{
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800" />
}
else
{
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800" />
}

KBVault.Web/Views/Shared/_Admin_Layout.cshtml
@using KBVault.Dal.Entities
@{
    KbUser CurrentUserInfo = KBVaultHelperFunctions.UserAsKbUser(Context.User);
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - KBVault</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width" />
    
    @*if (Request.Browser.Browser.Contains("InternetExplorer"))
     {
        <meta http-equiv="x-ua-compatible" content="IE=11" />
     } *@
        
    @{ Html.RenderPartial("GoogleFonts"); }     
    @Styles.Render("~/admin/css")       
</head>
 <body class="skin-blue">
     
    <header class="header">
        <a href='@Url.Action("Index", "Dashboard")' class="logo">        
            <img src='@Url.Content("~/Assets/img/vault.png")' width="48" /> KBVault
        </a>
        <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-right">
                <ul class="nav navbar-nav">

                    <li class="dropdown user user-menu">
                        <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                            <img src="@CurrentUserInfo.GravatarImageUrl" width="16" />                            
                            <span>@CurrentUserInfo.Name @CurrentUserInfo.LastName<i class="caret"></i></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header bg-light-blue">
                                <img src="@CurrentUserInfo.GravatarImageUrl" class="img-circle"/>
                                <p>@CurrentUserInfo.Name @CurrentUserInfo.LastName</p>
                            </li>                           
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="@Url.Action("MyProfile", "Account")" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href='@Url.Action("Logout", "Account")' class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>

                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
        <aside class="left-side sidebar-offcanvas">
            <section class="sidebar"> 
                <ul class="sidebar-menu">
                    @if (KBVaultHelperFunctions.IsAdmin(Context.User) || KBVaultHelperFunctions.IsManager(Context.User))
                    {
                    <li>
                        <div>
                            <a href='@Url.Action("Index", "Settings")'>
                                <i class="fa fa-gear"></i> <span>@UIResources.LeftSideBarSettings</span>
                            </a>
                        </div>
                    </li>
                    }
                    <li>
                        <div>
                            <a href='@Url.Action("Create", "Article")'>
                                <i class="fa fa-pencil"></i> <span>@UIResources.LeftSidebarCreateArticle</span>
                            </a>
                        </div>
                    </li>
                    @if (KBVaultHelperFunctions.IsAdmin(Context.User) || KBVaultHelperFunctions.IsManager(Context.User))
                    {
                    <li>     
                        <div>
                            <a href='@Url.Action("Create", "Category")'>
                                <i class="fa fa-plus"></i> <span>@UIResources.LeftSidebarCreateCategory</span>
                            </a>
                        </div>                       
                    </li>
                    }
                    <li class="treeview active">                                                
                        <div>
                            <a href="#" class="trigger-item">
                                <i class="fa fa-folder"></i>
                                <span>@UIResources.LeftSidebarCategoryListTitle</span>                                                                                                                                     
                            </a>                                
                       </div>      
                        
                        @KBVaultHelperFunctions.CreateCategoryMenu()
                        
                    </li>
                    @if (KBVaultHelperFunctions.IsAdmin(Context.User))
                    {
                    <li>
                        <div>
                            <a href='@Url.Action("Users", "Account")'>
                                <i class="fa fa-user"></i>
                                @UIResources.LeftSidebarUserMenuTitle
                            </a>
                        </div>
                    </li>
                    }
                    @if (KBVaultHelperFunctions.IsAdmin(Context.User) || KBVaultHelperFunctions.IsManager(Context.User))
                    {
                    <li>
                        <div>
                            <a href='@Url.Action("List", "Tag")'>
                                <i class="fa fa-tag"></i>
                                @UIResources.LeftSideBarTagsTitle
                            </a>
                        </div>
                    </li>
                    }
                    @if (KBVaultHelperFunctions.IsAdmin(Context.User))
                    {
                    <li>
                        <div>
                            <a href='@Url.Action("Index", "Activity")'>
                                <i class="fa fa-desktop"></i>
                                @UIResources.LeftSideBarActivitiesTitle
                            </a>
                        </div>
                    </li>
                        <li>
                            <div>
                                <a href="@Url.Action("Index","Backup")">
                                    <i class="fa fa-briefcase"></i>
                                    @UIResources.LeftSideBarBackupTitle
                                </a>
                            </div>
                        </li>
                        <li>
                            <div>
                                <a href="@Url.Action("Index","Indexing")">
                                    <i class="fa fa-book"></i>
                                    @UIResources.IndexingLeftMenuTitle
                                </a>
                            </div>
                        </li>
                    }
                    
                </ul>
            </section>
        </aside>
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                @RenderSection("ContentHeader", required: false)                
            </section>

            <!-- Main content -->
            <section class="content">
                @if (ViewBag.ShowOperationMessage != null && ViewBag.ShowOperationMessage)
                {
                    <div class="alert alert-success alert-dismissable">
                        <i class="fa fa-check"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @ViewBag.OperationMessage
                    </div>
                }
                 @if (ViewBag.ShowErrorMessage != null && ViewBag.ShowErrorMessage)
                 {
                    <div class="alert alert-danger alert-dismissable">
                        <i class="fa fa-check"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @ViewBag.ErrorMessage
                    </div>
                 }
                @RenderBody()
            </section>
        </aside>
    </div>
    
    @Scripts.Render("~/admin/js")     
     <script src="~/signalr/hubs"></script>
    <script>
            $(document).ready(function () {                
                @RenderSection("Scripts", required: false)
            });
        </script>
</body>
</html>

KBVault.Web/Views/Shared/_Layout.cshtml
@{
    var searchTerm = "";
    
    if(  ViewBag.SearchTerm != null )
    {
        searchTerm = ViewBag.SearchTerm;
    }
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge;" /> 
    
     
    @{ Html.RenderPartial("GoogleFonts"); }
    @Styles.Render("~/public/css")     
    @RenderSection("CssHeader", required: false)
    
    <script type="text/javascript">
        var KB_SearchUrl = "@Url.Action("Ajax","Search")";
    </script>
    
</head>
<body>
                 
    <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">@UIResources.MainMenuBootstrapToogleTitle</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index","Home")">@ViewBag.CompanyName</a>
        </div>
        <div class="navbar-collapse collapse">   
            <ul class="nav navbar-nav">  
                @KBVaultHelperFunctions.CreateBootstrapCategoryMenu()
             </ul>      
        </div>
    </div>        
    <div class="container">
        <div class="row">
            @*
            <div class="col-lg-12 page-header">            
                <h1>
                    @ViewBag.CompanyName
                    <small>@ViewBag.TagLine</small>
                </h1>    
                <p runat="server" id="htmlJumbotronText" class="lead">@ViewBag.JumbotronText</p>            
            </div>        
            *@
            
            @using (Html.BeginForm("Do", "Search", FormMethod.Post, new { id = "SearchForm" }))
            {
                <div class="input-group">       
                    <input type="hidden" name="ArticleId" id="ArticleId" value="" />
                    <input type="text" class="form-control search-control" name="SearchKeyword" placeholder="Enter search text" ID="txtSearch" value="@searchTerm" />
                        <span class="input-group-btn">
                            <input type="submit" id="btnDoSearch" class="btn btn-default" value="Search" />
                        </span>
                </div>             
            }    
            
        </div>

        <br />
        @RenderBody()   
       
    </div>
    <div id="footer">
        Built by KbVault
    </div>
        
    @Scripts.Render("~/public/js")
    @RenderSection("scripts", required: false)
    
    @if( !String.IsNullOrEmpty(ViewBag.AnalyticsAccount) )
    {
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', '@ViewBag.AnalyticsAccount', 'auto');
            ga('send', 'pageview');
        </script>
    }
    
</body>
</html>